version: "3.8"
services:
  rag:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app:delegated
      - ./pdfs:/app/pdfs
      - ./vectorstores:/app/vectorstores
      - ./vector_metadata.db:/app/vector_metadata.db
    restart: unless-stopped
